### ISSUE TITLE
simple axum server demo

### ISSUE THREAD

**Issue by sycamoreoak** [1Password/passkey-rs#55]
Would it be possible to get a simple axum server backend implementation (with a minimalist javascript frontend implementation)?

**Comment by Progdrasil** [comment]
The goal of this library is really to be a client and authenticator implementation. If you want to implement passkeys on your server to authenticate your users, I highly recommend [webauthn-rs](https://crates.io/crates/webauthn-rs). 

The reason for this is because the Relying party side (webauthn-rs) and the client/authenticator side have very different needs and requirements. Webauthn-rs is very strict in it's request types, and for good reason, so that it is hard for developers to make non-spec compliant requests. On the other hand this library, while type safe, allow requests and responses to deserialize from many different spec breaking formats in order to support all the varying implementations out there.

Webauthn-rs even has an [axum example](https://github.com/kanidm/webauthn-rs/tree/master/tutorial/server/axum) for your needs!
